### ISSUE TITLE
getting this error while running the 4nalyzer

### ISSUE THREAD

**Issue by sagarKasarapu** [Picodes/4naly3er#21]
command 

yarn analyze 2023-02-ethos scope.txt

scope.txt

Ethos-Core/contracts/CollateralConfig.sol
Ethos-Core/contracts/BorrowerOperations.sol
Ethos-Core/contracts/TroveManager.sol
Ethos-Core/contracts/ActivePool.sol
Ethos-Core/contracts/StabilityPool.sol
Ethos-Core/contracts/LQTY/CommunityIssuance.sol
Ethos-Core/contracts/LQTY/LQTYStaking.sol
Ethos-Core/contracts/LUSDToken.sol
Ethos-Vault/contracts/ReaperVaultV2.sol
Ethos-Vault/contracts/ReaperVaultERC4626.sol
Ethos-Vault/contracts/abstract/ReaperBaseStrategyV4.sol
Ethos-Vault/contracts/ReaperStrategyGranarySupplyOnly.sol

/mnt/e/web3/tools/4naly3er/node_modules/solc-0.8.17/soljson.js:925
    getWasmTableEntry(index)(a1, a2, a3, a4);
                            ^
TypeError: Cannot read properties of undefined (reading 'contents')
    at /mnt/e/web3/tools/4naly3er/node_modules/solc-0.8.17/wrapper.js:106:31
    at wasm://wasm/04f5a63e:wasm-function[34043]:0xe75c3a
    at invoke_viiii (/mnt/e/web3/tools/4naly3er/node_modules/solc-0.8.17/soljson.js:925:29)
    at wasm://wasm/04f5a63e:wasm-function[25253]:0x9bbaec
    at invoke_viii (/mnt/e/web3/tools/4naly3er/node_modules/solc-0.8.17/soljson.js:853:29)
    at wasm://wasm/04f5a63e:wasm-function[11985]:0x38c779
    at wasm://wasm/04f5a63e:wasm-function[25244]:0x9ba3b3
    at invoke_iii (/mnt/e/web3/tools/4naly3er/node_modules/solc-0.8.17/soljson.js:907:36)
    at wasm://wasm/04f5a63e:wasm-function[24956]:0x9679e5
    at invoke_viii (/mnt/e/web3/tools/4naly3er/node_modules/solc-0.8.17/soljson.js:853:29)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

**Comment by carlitox477** [comment]
Same question

**Comment by carlitox477** [comment]
According to discord user 100proof#3382 the issue happens only in windows.

As a windows user I just opted to run the corresponding command inside wsl and it worked perfect

**Comment by arialblack14** [comment]
Well, I am running Linux Mint 20.3 and I am getting this issue as well.

**Comment by NikolaVelevjs** [comment]
is there an update?

**Comment by B353N** [comment]
Same on Mac

**Comment by zaevlad** [comment]
Same issue on Windows and Ubuntu

**Comment by oliwiaanna03** [comment]
Same on Mac. @sagarKasarapu Is there any updates on this issue? thanks.

**Comment by devival** [comment]
any updates? Same issue on windows/ubuntu/mac

**Comment by packaging03** [comment]
This is 2025, and I am still getting this issue on my Mac. Is there any update on this issue?
