### ISSUE TITLE
TypeError: Cannot read property 'contents' of undefined, TypeError: Cannot read property 'includes' of undefined

### ISSUE THREAD

**Issue by gsangeryee** [Picodes/4naly3er#9]
When I run `4naly3er` in [2023-01-astaria](https://code4rena.com/contests/2023-01-astaria-contest) and [2023-01-ondo](https://github.com/code-423n4/2023-01-ondo). I got the following errors.

2023-01-astaria
```
    getWasmTableEntry(index)(a1, a2, a3, a4);
                            ^
TypeError: Cannot read property 'contents' of undefined

    at /4naly3er/node_modules/solc-0.8.17/wrapper.js:106:31
    at <anonymous>:wasm-function[34043]:0xe75c3a
    at invoke_viiii (/4naly3er/node_modules/solc-0.8.17/soljson.js:925:29)
    at <anonymous>:wasm-function[25253]:0x9bbaec
    at invoke_viii (/4naly3er/node_modules/solc-0.8.17/soljson.js:853:29)
    at <anonymous>:wasm-function[11985]:0x38c779
    at <anonymous>:wasm-function[25244]:0x9ba3b3
    at invoke_iii (/4naly3er/node_modules/solc-0.8.17/soljson.js:907:36)
    at <anonymous>:wasm-function[24956]:0x9679e5
    at invoke_viii (/4naly3er/node_modules/solc-0.8.17/soljson.js:853:29)
error Command failed with exit code 1.
```

2023-01-ondo
```
    contract.linearizedBaseContracts.includes(contractId) &&
                                           ^
TypeError: Cannot read property 'includes' of undefined
    at topLevelFiles (/4naly3er/src/utils.ts:59:44)
    at Object.detector (/4naly3er/src/issues/GAS/uselessInternal.ts:35:57)
    at analyze (/4naly3er/src/analyze.ts:39:25)
    at main (/4naly3er/src/index.ts:64:22)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
error Command failed with exit code 1.

```

**Comment by Picodes** [comment]
Thank you :)
